version: '3.7'
services:
  mongodb_container:
    image: arm64v8/mongo:4.4.18
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - /home/davie/volumes/mongodb:/data/db
